# Generated by cine-ir (cinematography-ir) — do not edit; re-run `cine-ir render blender`.
#
# Builds a clay-proxy scene from Solved Camera IR and exports conditioning
# passes (beauty / depth / normal / id / vector / openpose). Run with:
#     blender --background --factory-startup --python build.py
#
# All coordinates in PAYLOAD are already in Blender world space
# (X right, Y forward, Z up, metres). Cameras: local -Z forward, +Y up.
# Subject proxies: local +Y forward, +Z up, +X to the subject's right.

import json
import math
import os
import sys

import bpy
from mathutils import Matrix, Vector

PAYLOAD = json.loads('__PAYLOAD_JSON__')

# OpenPose COCO-18 keypoints (index: name) and limb connectivity/colours,
# matching the reference `draw_bodypose` used by ControlNet preprocessors.
KEYPOINT_NAMES = [
    "nose", "neck", "r_shoulder", "r_elbow", "r_wrist", "l_shoulder", "l_elbow",
    "l_wrist", "r_hip", "r_knee", "r_ankle", "l_hip", "l_knee", "l_ankle",
    "r_eye", "l_eye", "r_ear", "l_ear",
]
LIMBS = [
    (1, 2), (1, 5), (2, 3), (3, 4), (5, 6), (6, 7), (1, 8), (8, 9), (9, 10),
    (1, 11), (11, 12), (12, 13), (1, 0), (0, 14), (14, 16), (0, 15), (15, 17),
]
POSE_COLORS = [
    (255, 0, 0), (255, 85, 0), (255, 170, 0), (255, 255, 0), (170, 255, 0),
    (85, 255, 0), (0, 255, 0), (0, 255, 85), (0, 255, 170), (0, 255, 255),
    (0, 170, 255), (0, 85, 255), (0, 0, 255), (85, 0, 255), (170, 0, 255),
    (255, 0, 255), (255, 0, 170), (255, 0, 85),
]


def srgb_to_linear(c):
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def linear_rgb(rgb):
    return tuple(srgb_to_linear(float(c)) for c in rgb) + (1.0,)


def keypoints(width, depth, height):
    """Standing A-pose keypoints in subject-local space (x right, y forward, z up)."""
    w, h = width, height
    x_sho, x_hip = 0.45 * w, 0.20 * w
    return [
        Vector((0.0, 0.06 * h, 0.92 * h)),          # 0 nose
        Vector((0.0, 0.0, 0.85 * h)),               # 1 neck
        Vector((x_sho, 0.0, 0.82 * h)),             # 2 r_shoulder
        Vector((0.50 * w, 0.0, 0.64 * h)),          # 3 r_elbow
        Vector((0.52 * w, 0.05 * h, 0.47 * h)),     # 4 r_wrist
        Vector((-x_sho, 0.0, 0.82 * h)),            # 5 l_shoulder
        Vector((-0.50 * w, 0.0, 0.64 * h)),         # 6 l_elbow
        Vector((-0.52 * w, 0.05 * h, 0.47 * h)),    # 7 l_wrist
        Vector((x_hip, 0.0, 0.52 * h)),             # 8 r_hip
        Vector((x_hip, 0.0, 0.28 * h)),             # 9 r_knee
        Vector((x_hip, 0.0, 0.03 * h)),             # 10 r_ankle
        Vector((-x_hip, 0.0, 0.52 * h)),            # 11 l_hip
        Vector((-x_hip, 0.0, 0.28 * h)),            # 12 l_knee
        Vector((-x_hip, 0.0, 0.03 * h)),            # 13 l_ankle
        Vector((0.04 * h, 0.07 * h, 0.94 * h)),     # 14 r_eye
        Vector((-0.04 * h, 0.07 * h, 0.94 * h)),    # 15 l_eye
        Vector((0.07 * h, 0.02 * h, 0.93 * h)),     # 16 r_ear
        Vector((-0.07 * h, 0.02 * h, 0.93 * h)),    # 17 l_ear
    ]


# --------------------------------------------------------------------------
# Materials
# --------------------------------------------------------------------------

def clay_material(name, rgb):
    mat = bpy.data.materials.new(name)
    bsdf = mat.node_tree.nodes.get("Principled BSDF")
    bsdf.inputs["Base Color"].default_value = linear_rgb(rgb)
    bsdf.inputs["Roughness"].default_value = 0.85
    return mat


def emission_material(name, rgb, strength=1.0):
    mat = bpy.data.materials.new(name)
    nodes = mat.node_tree.nodes
    links = mat.node_tree.links
    nodes.clear()
    out = nodes.new("ShaderNodeOutputMaterial")
    emit = nodes.new("ShaderNodeEmission")
    emit.inputs["Color"].default_value = linear_rgb(rgb)
    emit.inputs["Strength"].default_value = strength
    links.new(emit.outputs["Emission"], out.inputs["Surface"])
    return mat


def object_color_material():
    """Emits each object's `color` — the segmentation/id override."""
    mat = bpy.data.materials.new("cine_seg_override")
    nodes = mat.node_tree.nodes
    links = mat.node_tree.links
    nodes.clear()
    out = nodes.new("ShaderNodeOutputMaterial")
    emit = nodes.new("ShaderNodeEmission")
    info = nodes.new("ShaderNodeObjectInfo")
    links.new(info.outputs["Color"], emit.inputs["Color"])
    links.new(emit.outputs["Emission"], out.inputs["Surface"])
    return mat


def camera_normal_material():
    """Emits camera-space normals as (n + 1) / 2 — the normal-map override."""
    mat = bpy.data.materials.new("cine_normal_override")
    nodes = mat.node_tree.nodes
    links = mat.node_tree.links
    nodes.clear()
    out = nodes.new("ShaderNodeOutputMaterial")
    emit = nodes.new("ShaderNodeEmission")
    geometry = nodes.new("ShaderNodeNewGeometry")
    transform = nodes.new("ShaderNodeVectorTransform")
    transform.vector_type = "NORMAL"
    transform.convert_from = "WORLD"
    transform.convert_to = "CAMERA"
    remap = nodes.new("ShaderNodeVectorMath")
    remap.operation = "MULTIPLY_ADD"
    # Cycles' camera space points +Z along the view direction, so flip Z to
    # get the conventional "z toward camera" normal map (see manifest.json).
    remap.inputs[1].default_value = (0.5, 0.5, -0.5)
    remap.inputs[2].default_value = (0.5, 0.5, 0.5)
    links.new(geometry.outputs["Normal"], transform.inputs["Vector"])
    links.new(transform.outputs["Vector"], remap.inputs[0])
    links.new(remap.outputs["Vector"], emit.inputs["Color"])
    links.new(emit.outputs["Emission"], out.inputs["Surface"])
    return mat


# --------------------------------------------------------------------------
# Geometry helpers
# --------------------------------------------------------------------------

def link_only(obj, collection):
    for existing in list(obj.users_collection):
        existing.objects.unlink(obj)
    collection.objects.link(obj)


def finish(obj, parent, collection, material, color, pass_index):
    obj.parent = parent
    obj.color = color
    obj.pass_index = pass_index
    if material is not None:
        obj.data.materials.append(material)
    link_only(obj, collection)
    return obj


def add_sphere(location, radius, **kw):
    bpy.ops.mesh.primitive_uv_sphere_add(radius=radius, segments=16, ring_count=8, location=location)
    obj = bpy.context.active_object
    return finish(obj, **kw)


def add_box(location, size, **kw):
    bpy.ops.mesh.primitive_cube_add(size=1.0, location=location)
    obj = bpy.context.active_object
    obj.scale = size
    return finish(obj, **kw)


def add_cylinder_between(p1, p2, radius, **kw):
    delta = p2 - p1
    length = max(delta.length, 1e-4)
    bpy.ops.mesh.primitive_cylinder_add(vertices=12, radius=radius, depth=length, location=(p1 + p2) / 2.0)
    obj = bpy.context.active_object
    obj.rotation_mode = "QUATERNION"
    obj.rotation_quaternion = delta.to_track_quat("Z", "Y")
    return finish(obj, **kw)


def add_cone(location, radius, depth, direction, **kw):
    bpy.ops.mesh.primitive_cone_add(vertices=12, radius1=radius, radius2=0.0, depth=depth, location=location)
    obj = bpy.context.active_object
    obj.rotation_mode = "QUATERNION"
    obj.rotation_quaternion = Vector(direction).to_track_quat("Z", "Y")
    return finish(obj, **kw)


def build_character(subject, parent, body_collection, skeleton_collection, material, color, pass_index):
    w, d, h = subject["dimensions"]
    kp = keypoints(w, d, h)
    kw = dict(parent=parent, collection=body_collection, material=material, color=color, pass_index=pass_index)

    add_sphere(kp[0] + Vector((0.0, -0.06 * h, 0.0)), 0.10 * h, **kw)            # head
    torso = add_cylinder_between(Vector((0.0, 0.0, 0.50 * h)), Vector((0.0, 0.0, 0.84 * h)), 0.45 * w, **kw)
    torso.scale = (torso.scale.x, torso.scale.y * max(d / max(w, 1e-4), 0.3), torso.scale.z)
    add_cylinder_between(Vector((0.0, 0.0, 0.44 * h)), Vector((0.0, 0.0, 0.52 * h)), 0.40 * w, **kw)  # pelvis
    add_cone(kp[0] + Vector((0.0, 0.03 * h, -0.01 * h)), 0.025 * h, 0.06 * h, (0.0, 1.0, 0.0), **kw)   # nose: facing cue
    limb_radius = 0.045 * h
    for a, b in [(2, 3), (3, 4), (5, 6), (6, 7), (8, 9), (9, 10), (11, 12), (12, 13)]:
        add_cylinder_between(kp[a], kp[b], limb_radius, **kw)
        add_sphere(kp[b], limb_radius, **kw)

    # OpenPose skeleton: emissive limbs and joints, rendered on their own view layer.
    if skeleton_collection is not None:
        joint_radius = 0.022 * h
        limb_r = 0.014 * h
        for index, (a, b) in enumerate(LIMBS):
            mat = emission_material(f"pose_limb_{subject['id']}_{index}", [c / 255.0 for c in POSE_COLORS[index]])
            add_cylinder_between(kp[a], kp[b], limb_r, parent=parent, collection=skeleton_collection,
                                 material=mat, color=color, pass_index=0)
        for index, point in enumerate(kp):
            mat = emission_material(f"pose_joint_{subject['id']}_{index}", [c / 255.0 for c in POSE_COLORS[index]])
            add_sphere(point, joint_radius, parent=parent, collection=skeleton_collection,
                       material=mat, color=color, pass_index=0)


def build_proxy(subject, parent, body_collection, skeleton_collection, material, color, pass_index):
    kind = subject["kind"]
    w, d, h = subject["dimensions"]
    kw = dict(parent=parent, collection=body_collection, material=material, color=color, pass_index=pass_index)
    if kind == "character":
        build_character(subject, parent, body_collection, skeleton_collection, material, color, pass_index)
    elif kind == "vehicle":
        add_box(Vector((0.0, 0.0, 0.30 * h)), (w, d, 0.60 * h), **kw)
        add_box(Vector((0.0, -0.10 * d, 0.78 * h)), (0.85 * w, 0.50 * d, 0.44 * h), **kw)
        add_cone(Vector((0.0, 0.5 * d, 0.30 * h)), 0.15 * h, 0.10 * d, (0.0, 1.0, 0.0), **kw)
    elif kind == "screen":
        add_box(Vector((0.0, 0.0, 0.5 * h)), (w, max(d, 0.02), h), **kw)
    elif kind == "environment":
        add_box(Vector((0.0, 0.0, 0.005)), (w, d, 0.01), **kw)
    elif kind == "abstract":
        add_sphere(Vector((0.0, 0.0, 0.5 * h)), 0.5 * min(w, h, d), **kw)
    else:  # prop
        add_box(Vector((0.0, 0.0, 0.5 * h)), (w, d, h), **kw)


# --------------------------------------------------------------------------
# Scene assembly
# --------------------------------------------------------------------------

def iter_action_fcurves(action):
    # Blender 4.4+ creates layered actions. Their curves live inside channel
    # bags instead of the legacy Action.fcurves collection retained by older
    # Blender versions.
    legacy_fcurves = getattr(action, "fcurves", None)
    if legacy_fcurves is not None:
        yield from legacy_fcurves
        return
    for layer in action.layers:
        for strip in layer.strips:
            for channelbag in strip.channelbags:
                yield from channelbag.fcurves


def linearise_fcurves(id_data):
    action = id_data.animation_data.action if id_data.animation_data else None
    if action is None:
        return
    for fcurve in iter_action_fcurves(action):
        for point in fcurve.keyframe_points:
            point.interpolation = "LINEAR"


def basis_matrix(values, offset):
    rows = values[offset:offset + 9]
    return Matrix(((rows[0], rows[1], rows[2]), (rows[3], rows[4], rows[5]), (rows[6], rows[7], rows[8])))


def set_pose(obj, location, basis, scale, frame):
    obj.location = Vector(location)
    obj.rotation_mode = "QUATERNION"
    obj.rotation_quaternion = basis.to_quaternion()
    obj.scale = Vector(scale)
    obj.keyframe_insert("location", frame=frame)
    obj.keyframe_insert("rotation_quaternion", frame=frame)
    obj.keyframe_insert("scale", frame=frame)


def build_scene(p):
    bpy.ops.wm.read_factory_settings(use_empty=True)
    scene = bpy.context.scene
    scene.name = p["scene_id"]
    render = p["render"]

    # `fps` is a 16-bit int in Blender; express 24000/1001 as 24 / 1.001.
    num, den = int(p["fps_numerator"]), max(1, int(p["fps_denominator"]))
    fps = max(1, int(round(num / den)))
    scene.render.fps = fps
    scene.render.fps_base = fps * den / num
    scene.frame_start = int(render["frame_range"][0])
    scene.frame_end = int(render["frame_range"][1])
    scene.render.resolution_x = int(render["resolution"][0])
    scene.render.resolution_y = int(render["resolution"][1])
    scene.render.resolution_percentage = 100
    scene.render.engine = "CYCLES"
    scene.cycles.samples = int(render["samples"])
    scene.cycles.seed = 0
    scene.cycles.use_denoising = False
    scene.cycles.device = "CPU"
    scene.render.use_motion_blur = False
    scene.render.film_transparent = False
    scene.render.use_compositing = True
    scene.render.use_sequencer = False
    scene.view_settings.view_transform = "Standard"
    scene.view_settings.look = "None"
    scene.display_settings.display_device = "sRGB"

    world = bpy.data.worlds.new("cine_world")
    background = world.node_tree.nodes.get("Background")
    background.inputs["Color"].default_value = (0.0, 0.0, 0.0, 1.0)
    background.inputs["Strength"].default_value = 1.0
    scene.world = world

    bodies = bpy.data.collections.new("cine_bodies")
    skeletons = bpy.data.collections.new("cine_skeletons")
    cameras = bpy.data.collections.new("cine_cameras")
    for collection in (bodies, skeletons, cameras):
        scene.collection.children.link(collection)

    # Key light + fill so the beauty pass reads as clay, not silhouettes.
    sun_data = bpy.data.lights.new("cine_key", type="SUN")
    sun_data.energy = 3.0
    sun = bpy.data.objects.new("cine_key", sun_data)
    sun.rotation_euler = (math.radians(50.0), 0.0, math.radians(35.0))
    scene.collection.objects.link(sun)
    fill_data = bpy.data.lights.new("cine_fill", type="SUN")
    fill_data.energy = 1.0
    fill = bpy.data.objects.new("cine_fill", fill_data)
    fill.rotation_euler = (math.radians(60.0), 0.0, math.radians(-120.0))
    scene.collection.objects.link(fill)

    # Floor: gives depth/normal passes a ground plane; id 0 = background.
    bpy.ops.mesh.primitive_plane_add(size=60.0, location=(0.0, 0.0, 0.0))
    floor = bpy.context.active_object
    floor.name = "cine_floor"
    floor.color = (0.0, 0.0, 0.0, 1.0)  # black in the id pass: background class
    floor.pass_index = 0
    floor.data.materials.append(clay_material("cine_floor", (0.45, 0.45, 0.45)))
    link_only(floor, bodies)

    # Subjects.
    for subject in p["subjects"]:
        empty = bpy.data.objects.new(f"subject_{subject['id']}", None)
        empty.empty_display_type = "ARROWS"
        empty.empty_display_size = 0.3
        cameras_or_bodies = bodies
        cameras_or_bodies.objects.link(empty)
        color = linear_rgb(subject["color"])
        material = clay_material(f"clay_{subject['id']}", subject["color"])
        skeleton_collection = skeletons if subject["kind"] == "character" else None
        build_proxy(subject, empty, bodies, skeleton_collection, material, color, int(subject["pass_index"]))
        for offset, values in enumerate(subject["frames"]):
            frame = int(p["frame_start"]) + offset
            set_pose(empty, values[0:3], basis_matrix(values, 3), values[12:15], frame)
        linearise_fcurves(empty)

    # Cameras: one per shot, switched with timeline markers.
    first_camera = None
    for shot in p["shots"]:
        data = bpy.data.cameras.new(f"cam_{shot['id']}")
        data.sensor_fit = "HORIZONTAL"
        data.sensor_width = float(shot["sensor_width_mm"])
        data.clip_start = 0.05
        data.clip_end = 1000.0
        data.dof.use_dof = bool(render["use_dof"])
        data.dof.aperture_fstop = float(shot["aperture_f"])
        cam = bpy.data.objects.new(f"cam_{shot['id']}", data)
        cameras.objects.link(cam)
        for offset, values in enumerate(shot["frames"]):
            frame = int(shot["frame_start"]) + offset
            cam.location = Vector(values[0:3])
            cam.rotation_mode = "QUATERNION"
            cam.rotation_quaternion = basis_matrix(values, 3).to_quaternion()
            cam.keyframe_insert("location", frame=frame)
            cam.keyframe_insert("rotation_quaternion", frame=frame)
            data.lens = float(values[12])
            data.dof.focus_distance = float(values[13])
            data.keyframe_insert("lens", frame=frame)
            data.dof.keyframe_insert("focus_distance", frame=frame)
        linearise_fcurves(cam)
        linearise_fcurves(data)
        marker = scene.timeline_markers.new(shot["id"], frame=int(shot["frame_start"]))
        marker.camera = cam
        if first_camera is None:
            first_camera = cam
    scene.camera = first_camera
    return scene, bodies, skeletons


# --------------------------------------------------------------------------
# View layers and compositor
# --------------------------------------------------------------------------

def exclude(view_layer, collection, excluded):
    layer_collection = view_layer.layer_collection.children.get(collection.name)
    if layer_collection is not None:
        layer_collection.exclude = excluded


def configure_passes(scene, bodies, skeletons, passes, out_dir, near, far):
    main = scene.view_layers[0]
    main.name = "main"
    main.use_pass_z = "depth" in passes
    main.use_pass_vector = "vector" in passes
    main.use_pass_object_index = True
    exclude(main, skeletons, True)

    layers = {"main": main}
    if "normal" in passes:
        layer = scene.view_layers.new("normal")
        layer.material_override = camera_normal_material()
        layer.samples = 1
        exclude(layer, skeletons, True)
        layers["normal"] = layer
    if "id" in passes:
        layer = scene.view_layers.new("id")
        layer.material_override = object_color_material()
        layer.samples = 1
        exclude(layer, skeletons, True)
        layers["id"] = layer
    if "openpose" in passes:
        layer = scene.view_layers.new("openpose")
        layer.samples = 1
        exclude(layer, bodies, True)
        layers["openpose"] = layer

    tree = bpy.data.node_groups.new("CineIRCompositor", type="CompositorNodeTree")
    tree.interface.new_socket(
        name="Image", in_out="OUTPUT", socket_type="NodeSocketColor")
    scene.compositing_node_group = tree

    def render_layer_node(name):
        node = tree.nodes.new("CompositorNodeRLayers")
        node.layer = name
        node.scene = scene
        return node

    def file_output(name, fmt, depth, color_mode, raw):
        node = tree.nodes.new("CompositorNodeOutputFile")
        node.directory = os.path.join(out_dir, name)
        node.file_name = "####"
        socket_type = "FLOAT" if color_mode == "BW" else "RGBA"
        # A non-empty item name is appended to every rendered filename in
        # Blender 5.2 (for example, 0000Image.png). Each node has one item, so
        # keep its name empty to preserve the manifest's ####.ext contract.
        node.file_output_items.new(socket_type, "")
        node.format.media_type = "IMAGE"
        node.format.file_format = fmt
        node.format.color_mode = color_mode
        node.format.color_depth = depth
        if fmt == "OPEN_EXR":
            node.format.exr_codec = "ZIP"
        node.format.color_management = "OVERRIDE"
        node.format.view_settings.view_transform = "Raw" if raw else "Standard"
        return node

    rl_main = render_layer_node("main")
    group_output = tree.nodes.new("NodeGroupOutput")
    tree.links.new(rl_main.outputs["Image"], group_output.inputs["Image"])
    if "beauty" in passes:
        node = file_output("beauty", "PNG", "8", "RGB", raw=False)
        tree.links.new(rl_main.outputs["Image"], node.inputs[0])
    if "depth" in passes:
        remap = tree.nodes.new("ShaderNodeMapRange")
        remap.clamp = True
        remap.inputs[1].default_value = float(near)   # From Min
        remap.inputs[2].default_value = float(far)    # From Max
        remap.inputs[3].default_value = 1.0           # To Min (near = white)
        remap.inputs[4].default_value = 0.0           # To Max (far = black)
        tree.links.new(rl_main.outputs["Depth"], remap.inputs[0])
        node = file_output("depth", "PNG", "16", "BW", raw=True)
        tree.links.new(remap.outputs[0], node.inputs[0])
    if "vector" in passes:
        node = file_output("vector", "OPEN_EXR", "32", "RGBA", raw=True)
        tree.links.new(rl_main.outputs["Vector"], node.inputs[0])
    for name in ("normal", "id", "openpose"):
        if name in passes:
            rl = render_layer_node(name)
            node = file_output(name, "PNG", "8", "RGB", raw=(name == "normal"))
            tree.links.new(rl.outputs["Image"], node.inputs[0])

    # The scene's own output is redundant with the File Output nodes; park it.
    scene.render.filepath = os.path.join(out_dir, "_composite", "####")
    scene.render.image_settings.file_format = "PNG"


def main():
    p = PAYLOAD
    render = p["render"]
    out_dir = render["output_dir"]
    os.makedirs(out_dir, exist_ok=True)
    scene, bodies, skeletons = build_scene(p)
    configure_passes(scene, bodies, skeletons, set(render["passes"]), out_dir,
                     render["depth_near_m"], render["depth_far_m"])
    bpy.ops.wm.save_as_mainfile(filepath=os.path.join(out_dir, "scene.blend"))
    bpy.ops.render.render(animation=True, write_still=False)
    with open(os.path.join(out_dir, "done.json"), "w", encoding="utf-8") as handle:
        json.dump({
            "blender_version": bpy.app.version_string,
            "scene_id": p["scene_id"],
            "frame_range": render["frame_range"],
            "passes": sorted(render["passes"]),
        }, handle, indent=2)


if __name__ == "__main__":
    try:
        main()
    except Exception as error:  # noqa: BLE001 — surface everything to the caller
        print(f"cine-ir blender build failed: {error!r}", file=sys.stderr)
        raise
